app/models.py
from . import db
from sqlalchemy.sql import func
from flask_login import UserMixin


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    title = db.Column(db.String())
    description = db.Column(db.String(160))
    text = db.Column(db.String())
    date = db.Column(db.DateTime(timezone=True), default=func.now())

    def __str__(self) -> str:
        return f"{self.author_id}, {self.title}, {self.date}"


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    articles = db.relationship("Article")

app/__init__.py
from flask import Flask
from flask.helpers import url_for
from flask_login import LoginManager, login_manager
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'qwertyuiop'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'

    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Article

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database')

app/auth.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from flask_login import login_user, login_required, logout_user, current_user
from . import db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            else:
                flash("Incorrect password, try again", category="error")
        else:
            flash("Email does not exist", category="error")

    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == "POST":
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exist', category='error')
        elif len(email) < 4:
            flash('Invalid email', category='error')
        elif len(firstName) < 2:
            flash('Invalid name', category='error')
        elif password1 != password2:
            flash('passwords do not match', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters', category='error')
        else:
            new_user = User(email=email, first_name=firstName, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created', category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

app/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from .models import Article
from flask_login import login_required, current_user
from . import db
import markdown

views = Blueprint('views', __name__)

@views.route('/')
def home():
    articles = Article.query.order_by(Article.date).all()
    return render_template('home.html', articles=articles, user=current_user)

@views.route('/create-article', methods=["GET", "POST"])
@login_required
def create_article():
    if request.method == "POST":
        article_title = request.form.get('title')
        article_description = request.form.get('description')
        article_text = request.form.get('text')

        if len(article_text) < 50:
            flash('Article is too short', category='error')
        elif len(article_text) < 5:
            flash('Article title too short', category='error')
        elif len(article_description) < 20:
            flash('Article description too short', category='error')
        else:
            new_article = Article(author_id=current_user.id, title=article_title, description=article_description, text=article_text)
            db.session.add(new_article)
            db.session.commit()
            flash("Article created", category='success')

            return redirect(url_for('views.home'))
    
    if request.method == "GET":
        return render_template('create_article.html', user=current_user)
    
    return redirect(url_for('views.home'))

@views.route('/delete/<int:id>')
@login_required
def delete(id):
    article_to_delete = Article.query.get_or_404(id)

    if article_to_delete:
        if article_to_delete.author_id == current_user.id:
            try:
                db.session.delete(article_to_delete)
                db.session.commit()
            except:
                flash("There was a problem deleting your article", category="error")
        else:
            flash('You cannot delete this article', category='error')
    
    return redirect(url_for('views.home'))

@views.route('/edit/<int:id>', methods=["GET","POST"])
@login_required
def edit_article(id):
    article_to_edit = Article.query.get_or_404(id)
    
    if request.method == "POST":
        if article_to_edit:
            if article_to_edit.author_id == current_user.id:
                try:
                    article_to_edit.title = request.form.get("title")
                    article_to_edit.description = request.form.get('description')
                    article_to_edit.text = request.form.get('text')
                    db.session.add(article_to_edit)
                    db.session.commit()
                    flash("Article edited", category="success")

                    return redirect(url_for('views.home'))
                except:
                    flash("There was a problem editing your article", category="error")
            else:
                flash('You cannot edit this article', category='error')
    elif request.method == "GET":
        if article_to_edit.author_id == current_user.id:
            return render_template("edit_article.html", article=article_to_edit, user=current_user)

    flash('You cannot edit this article', category='error')
    return redirect(url_for('views.home'))


@views.route('/article/<int:id>')
def article(id):
    article = Article.query.get_or_404(id)
    article.text = markdown.markdown(article.text)
    print(article)
    return render_template('article.html', article=article, user=current_user)

app/templates/article.html
{% extends "base.html" %} 

{% block title %}{% endblock %}

{% block content %}

<div class="page-content">
  <div class="grid-row">
    <div class="composer">

      {% if user.is_authenticated %}
      {% if user.id == article.author_id %}
      <a href="/delete/{{ article.id }}" class="button">DELETE</a>
      <a href="/edit/{{ article.id }}" class="button">EDIT</a>
      <br>
      <br>
      {% endif %}
      {% endif %}

      <div class="text">
        <h1 class="center">{{ article.title }}</h1>

        <div
          class="latest-article"
          style="text-align: justify; font-size: 20px;"
        >
          <div class="post-info">
            <span>{{ article.date }}</span><span><i class="fa fa-edit"></i>{{ article.author_id.first_name }}</span>
          </div>

          <br>

          {{ article.text|safe }}


        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Physic blog</title>

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="../static/css/animate.css" />
    <link rel="stylesheet" href="../static/css/font-awesome.css" />
    <link rel="stylesheet" href="../static/css/jquery.fancybox.css" />
    <link rel="stylesheet" href="../static/css/jquery.owl.carousel.css" />
    <link rel="stylesheet" href="../static/css/main.css" />

    <title>{% block title %}Pyshics for you{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark main-nav">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">

        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a href="/" class="nav-item nav-link" id="home"> Home </a>
          <a class="nav-item nav-link" href="{{ url_for('views.create_article') }}">write</a>
          <a href="/" class="nav-item nav-link" id="home">
            other discussions
          </a>
          <a href="/logout" class="nav-item nav-link" id="logout"> logout </a>
          {%else%}
          <a href="/" class="nav-item nav-link" id="home"> Home </a>
          <a href="/" class="nav-item nav-link" id="home">
            other discussions
          </a>
          <a href="/login" class="nav-item nav-link" id="login"> login </a>
          <a href="/sign-up" class="nav-item nav-link" id="signUp"> sign up </a>
          {% endif %}
        </div>

      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {%for category, message in messages%} {% if category == 'error'
    %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="success alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{%block content%} {% endblock %}</div>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/jquery-ui.min.js"></script>
    <script src="../static/js/jquery.migrate.min.js"></script>
    <script src="../static/js/jquery.isotope.min.js"></script>
    <script src="../static/js/jquery.form.min.js"></script>
    <script src="../static/js/jquery.validate.min.js"></script>
    <script src="../static/js/jquery.tweet.js"></script>
    <script src="../static/js/jquery.countdown.min.js"></script>
    <script src="../static/js/jquery.fancybox.pack.js"></script>
    <script src="../static/js/jquery.fancybox-media.js"></script>
    <script src="../static/js/jquery.ui.core.min.js"></script>
    <script src="../static/js/jquery.ui.widget.min.js"></script>
    <script src="../static/js/jquery.ui.mouse.min.js"></script>
    <script src="../static/js/jquery.ui.slider.min.js"></script>
    <script src="../static/js/jquery.owl.carousel.min.js"></script>
    <script src="../static/js/retina.min.js"></script>
    <script src="../static/js/wow.min.js"></script>
    <script src="../static/js/main.js"></script>
  </body>
</html>

app/templates/create_article.html
{% extends "base.html" %}

{% block content %}
<form class="feedback" action="" method="POST" >
    <h3>
        Write an article
    </h3>
    <div class="form-submit">
        <label for="title">Title</label>
        <input type="text"
        class="input-text"
        name="title"
        id="title"
        placeholder="Enter title">
    </div>
    <div class="form-submit">
        <label for="description">description</label>
        <input type="text"
        class="input-text"
        name="description"
        id="description"
        placeholder="Enter a short description of the article">
    </div>
    <div class="form-submit">
        <label for="text">write your article</label>
        <textarea name="text" id="text" cols="30" rows="25" class="feedback"></textarea>
    </div>
    <button class="button" type="submit">submit</button>
</form>

{% endblock %}

app/templates/edit_article.html
{% extends "base.html" %}

{% block content %}
<form class="feedback" action="" method="POST" >
    <h3>
        Edit your article
    </h3>
    <div class="form-submit">
        <label for="title">Title</label>
        <input type="text"
        class="input-text"
        name="title"
        id="title"
        value="{{ article.title }}">
    </div>
    <div class="form-submit">
        <label for="description">description</label>
        <input type="text"
        class="input-text"
        name="description"
        id="description"
        value="{{ article.description }}">
    </div>
    <div class="form-submit">
        <label for="text">write your article</label>
        <textarea name="text" id="text" cols="30" rows="25" class="feedback">{{ article.text }}</textarea>
    </div>
    <button class="button" type="submit">edit</button>
</form>

<a href="/article/{{ article.id }}" class="button">back</a>

{% endblock %}

app/templates/home.html
{% extends "base.html" %} 

{% block content %}

<div class="page-content">

  <div class="grid-row composer">
    <!-- text -->
    <div class="text intro">
      <h1 class="center">Pyshics for you</h1>
      <h2 class="center">blog made by students for students</h2>
    </div>
    <!--/ text -->
  </div>
</div>

<div class="page-content">
  <div class="grid-row">
    <!-- best reviews -->
    <div class="best-reviews">
        <h2>Main posts</h2>
        <div class="page-separator"></div>
        {%for article in articles%}
        <ul id="best-reviews" class="wow scale-to-top">
          <li class="wow scale-to-top">
            <h3><a href="/article/{{article.id}}">{{ article.title }}</a></h3>
            <div class="post-info">
              <span>{{ article.date }}</span>
              <span>{{ article.author_id.first_name }}</span>
              <p>{{ article.description }}</p>
            </div>
          </li>
          <div class="page-separator"></div>

        </ul>
        {% endfor %}
    </div>
    <!--/ best reviews -->
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form action="" method="post">
  <br />
  <h2 align="center">Login</h2>
  <br />
  <div class="page-separator"></div>
  <br>
  <div class="form-row grid-row">
    <label for="email">Email address</label>
    <input
      type="email"
      class="form-control"
      name="email"
      id="email"
      placedholder="Enter email"
    />
  </div>
  <br />
  <div class="form-row grid-row">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      name="password"
      id="password"
      placedholder="Enter password"
    />
  </div>
  <br />
  <div class="grid-row">
    <button type="submit" class="owl-buttons button">Login</button>
  </div>
</form>
{% endblock %}

app/templates/other_discussions.html
{% extends "base.html" %} 

{% block title %}Other discussions{% endblock %}

{% block content %}

<div class="page-content">
  <div class="grid-row">
    <div class="composer">
      <div class="text">
        <h1 class="center">title</h1>

        <div
          class="latest-article"
          style="text-align: justify; font-size: 20px"
        >
          <div class="post-info">
            <span>Date</span><span><i class="fa fa-edit"></i>author</span>
          </div>

          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quaerat
            officiis deleniti vero unde? Est magni debitis ducimus fugiat quo
            suscipit explicabo quam reiciendis voluptas sint, et qui hic
            accusantium itaque!
          </p>
          
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit.
            Consectetur est saepe praesentium error doloribus nisi eveniet
            explicabo dicta assumenda? Eligendi libero quasi saepe provident
            maiores omnis totam minima qui nemo!
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign up{% endblock %} {% block
content %}
<form action="" method="post">
  <br />
  <h2 align="center">sign up</h2>
  <br />
  <div class="page-separator"></div>
  <br>
  <div class="form-row grid-row">
    <label for="email">Email address</label>
    <input
      type="email"
      class="form-control"
      name="email"
      id="email"
      placedholder="Enter email"
    />
  </div>
  <br>
  <div class="form-row grid-row">
    <label for="firstName">first name</label>
    <input
      type="text"
      class="form-control"
      name="firstName"
      id="firstName"
      placedholder="Enter first name"
    />
  </div>
  <br>
  <div class="form-row grid-row">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      name="password1"
      id="password1"
      placedholder="Enter password"
    />
  </div>
  <br>
  <div class="form-row grid-row">
    <label for="password2">Confirm password</label>
    <input
      type="password"
      class="form-control"
      name="password2"
      id="password2"
      placedholder="Confirm password"
    />
  </div>
  <br />
  <div class="grid-row">
    <button type="submit" class="owl-buttons button">Submit</button>
  </div>
</form>
{% endblock %}